CREATE TABLE public.product_events (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id text NOT NULL,
  event_name text NOT NULL,
  brand text NOT NULL,
  created_at timestamp without time zone DEFAULT now() NOT NULL,
  CONSTRAINT product_events_session_id_uuid_check
    CHECK (session_id ~* '^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'),
  CONSTRAINT product_events_event_name_check
    CHECK (event_name IN (
      'home_view',
      'chat_started',
      'trip_plan_completed',
      'checkout_viewed',
      'auth_started',
      'signup_completed',
      'trip_saved',
      'trip_hub_viewed',
      'splitta_opened'
    )),
  CONSTRAINT product_events_brand_check
    CHECK (brand IN ('byebro', 'byebride'))
);

CREATE INDEX product_events_created_at_idx
  ON public.product_events (created_at);

CREATE INDEX product_events_event_name_idx
  ON public.product_events (event_name);

ALTER TABLE public.product_events ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.product_events FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.product_events_id_seq FROM anon, authenticated;
