CREATE TABLE public.affiliate_clicks (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id text NOT NULL,
  provider text NOT NULL,
  placement text NOT NULL,
  brand text NOT NULL,
  destination text,
  monetized boolean NOT NULL,
  created_at timestamp without time zone DEFAULT now() NOT NULL,
  CONSTRAINT affiliate_clicks_session_id_uuid_check
    CHECK (session_id ~* '^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'),
  CONSTRAINT affiliate_clicks_provider_check
    CHECK (provider IN ('aviasales', 'booking', 'getyourguide')),
  CONSTRAINT affiliate_clicks_placement_check
    CHECK (placement IN (
      'checkout_flight',
      'checkout_hotel',
      'checkout_hotel_fallback',
      'checkout_experiences',
      'destinations',
      'experiences',
      'itinerary'
    )),
  CONSTRAINT affiliate_clicks_brand_check
    CHECK (brand IN ('byebro', 'byebride')),
  CONSTRAINT affiliate_clicks_destination_length_check
    CHECK (destination IS NULL OR char_length(destination) BETWEEN 1 AND 100)
);

CREATE INDEX affiliate_clicks_created_at_idx
  ON public.affiliate_clicks (created_at);

CREATE INDEX affiliate_clicks_provider_idx
  ON public.affiliate_clicks (provider);

ALTER TABLE public.affiliate_clicks ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.affiliate_clicks FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.affiliate_clicks_id_seq FROM anon, authenticated;
